import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/theme-provider"


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            forcedTheme="dark"
          >
          <header className="items-center p-4 gap-4 h-16">
            <div className='flex justify-between'>
                <div>
                Dpin Uptime
              </div>
              <div>
                <SignedOut>
                <SignInButton />
                <SignUpButton/>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
              </div>
            </div>
          </header>
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}