"""
Manual artist-level classification (language / genre / mood) built from domain
knowledge of Bollywood, Punjabi, and English music -- Spotify's export carries
no genre/mood metadata, so this is a curated lookup, not derived data.

Covers the top 200 artists by minutes played (~93% of total listening time).
Everything else falls into 'Unclassified'.

mood is only meaningful for Hindi/Punjabi entries per the user's instruction
to skip lyrical/emotional reading of English tracks (English gets a genre
split only: Pop/Rock/EDM/etc).
"""

# artist -> (language, genre, mood)
# language: English | Hindi | Punjabi | Other
# mood (Hindi/Punjabi only): Energetic | Romantic-Soft | Deep-Soulful | Nostalgic-Classic | None
ARTIST_TAGS = {
    # --- English ---
    "Taylor Swift": ("English", "Pop", None),
    "The Weeknd": ("English", "Pop/R&B", None),
    "Adele": ("English", "Pop/Soul", None),
    "ZAYN": ("English", "Pop/R&B", None),
    "Dua Lipa": ("English", "Pop/Dance", None),
    "Maroon 5": ("English", "Pop/Rock", None),
    "Katy Perry": ("English", "Pop", None),
    "AC/DC": ("English", "Rock", None),
    "Ariana Grande": ("English", "Pop", None),
    "Linkin Park": ("English", "Rock", None),
    "Marshmello": ("English", "EDM/Pop", None),
    "Olivia Rodrigo": ("English", "Pop/Rock", None),
    "Nickelback": ("English", "Rock", None),
    "Ellie Goulding": ("English", "Pop", None),
    "The Chainsmokers": ("English", "EDM/Pop", None),
    "Sia": ("English", "Pop", None),
    "OneRepublic": ("English", "Pop/Rock", None),
    "Clean Bandit": ("English", "EDM/Pop", None),
    "Zedd": ("English", "EDM", None),
    "Billie Eilish": ("English", "Pop/Alt", None),
    "Christina Perri": ("English", "Pop", None),
    "Coldplay": ("English", "Rock/Pop", None),
    "Meghan Trainor": ("English", "Pop", None),
    "Ed Sheeran": ("English", "Pop", None),
    "One Direction": ("English", "Pop", None),
    "Bebe Rexha": ("English", "Pop", None),
    "Demi Lovato": ("English", "Pop", None),
    "Arctic Monkeys": ("English", "Rock/Indie", None),
    "Lady Gaga": ("English", "Pop", None),
    "Conan Gray": ("English", "Pop/Indie", None),
    "Sam Smith": ("English", "Pop/Soul", None),
    "The Neighbourhood": ("English", "Alt Rock", None),
    "Charlie Puth": ("English", "Pop", None),
    "Calvin Harris": ("English", "EDM", None),
    "Avicii": ("English", "EDM", None),
    "Ava Max": ("English", "Pop", None),
    "Imagine Dragons": ("English", "Rock/Pop", None),
    "Harry Styles": ("English", "Pop/Rock", None),
    "Kavinsky": ("English", "Electronic/Synthwave", None),
    "Stephen Sanchez": ("English", "Indie/Pop", None),
    "Kelly Clarkson": ("English", "Pop", None),
    "Julia Michaels": ("English", "Pop", None),
    "Camila Cabello": ("English", "Pop", None),
    "Post Malone": ("English", "Hip-Hop/Pop", None),
    "Beyoncé": ("English", "Pop/R&B", None),
    "Dolly Parton": ("English", "Country", None),
    "Sasha Alex Sloan": ("English", "Indie/Pop", None),
    "Eminem": ("English", "Hip-Hop", None),
    "Miley Cyrus": ("English", "Pop/Rock", None),
    "Elton John": ("English", "Classic Rock/Pop", None),
    "Liam Payne": ("English", "Pop", None),
    "Tom Odell": ("English", "Indie/Piano Pop", None),
    "Phil Collins": ("English", "Classic Rock/Pop", None),
    "Rachel Platten": ("English", "Pop", None),
    "G-Eazy": ("English", "Hip-Hop", None),
    "The Kinks": ("English", "Classic Rock", None),
    "Maren Morris": ("English", "Country/Pop", None),
    "Queen": ("English", "Classic Rock", None),
    "Lana Del Rey": ("English", "Indie Pop", None),
    "Sabrina Carpenter": ("English", "Pop", None),
    "Modern Talking": ("English", "Synth-Pop", None),
    "David Guetta": ("English", "EDM", None),
    "Lord Huron": ("English", "Indie Folk/Rock", None),
    "Elliot James Reay": ("English", "Indie/Retro Pop", None),
    "Knife Party": ("English", "EDM", None),
    "Fort Atlantic": ("English", "Indie", None),
    "Dr. Dre": ("English", "Hip-Hop", None),
    "Macklemore": ("English", "Hip-Hop", None),
    "Justin Timberlake": ("English", "Pop/R&B", None),
    "Ruth B.": ("English", "Indie Pop", None),
    "Selena Gomez": ("English", "Pop", None),
    "Twenty One Pilots": ("English", "Alt Rock/Pop", None),
    "Ghost": ("English", "Rock/Metal", None),
    "Real Estate": ("English", "Indie Rock", None),
    "Enya": ("English", "Ambient/New Age", None),
    "RAIGN": ("English", "Cinematic/Electronic", None),
    "Apparat": ("English", "Electronic/Ambient", None),
    "Jasmine Thompson": ("English", "Pop/Indie", None),
    "Zaeden": ("English", "EDM", None),
    "BTS": ("Other", "K-Pop", None),
    "League of Legends": ("Other", "Game Soundtrack", None),

    # --- Punjabi ---
    "Diljit Dosanjh": ("Punjabi", "Modern Pop/Folk-Pop", "Energetic"),
    "Karan Aujla": ("Punjabi", "Modern Pop/Trap", "Energetic"),
    "Amrinder Gill": ("Punjabi", "Soft Romantic/Film", "Romantic-Soft"),
    "Shubh": ("Punjabi", "Modern R&B-Pop", "Deep-Soulful"),
    "Gurdas Maan": ("Punjabi", "Folk/Legend", "Nostalgic-Classic"),
    "Satinder Sartaaj": ("Punjabi", "Sufi/Poetic", "Deep-Soulful"),
    "Surjit Bindrakhia": ("Punjabi", "Old-School Bhangra", "Energetic"),
    "Mankirt Aulakh": ("Punjabi", "Modern Pop", "Energetic"),
    "Sidhu Moose Wala": ("Punjabi", "Modern/Rap-influenced", "Energetic"),
    "Nirvair Pannu": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Shivjot": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Ammy Virk": ("Punjabi", "Romantic/Film", "Romantic-Soft"),
    "AP Dhillon": ("Punjabi", "Modern R&B-Pop", "Deep-Soulful"),
    "Nimrat Khaira": ("Punjabi", "Romantic/Film", "Romantic-Soft"),
    "Tegi Pannu": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Amrit Maan": ("Punjabi", "Modern Pop", "Energetic"),
    "Harjit Harman": ("Punjabi", "Romantic/Film", "Romantic-Soft"),
    "Gippy Grewal": ("Punjabi", "Dance/Film", "Energetic"),
    "Jass Manak": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Babbu Maan": ("Punjabi", "Folk/Legend", "Deep-Soulful"),
    "Bir Singh": ("Punjabi", "Indie/Sufi-Folk", "Deep-Soulful"),
    "Jasmine Sandlas": ("Punjabi", "Modern Pop", "Energetic"),
    "Maninder Buttar": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Navaan Sandhu": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "Sharn": ("Punjabi", "Modern Pop", "Romantic-Soft"),
    "Balkar Sidhu": ("Punjabi", "Modern Pop", "Energetic"),
    "Garry Sandhu": ("Punjabi", "Modern Dance/Romantic", "Energetic"),
    "Gurnam Bhullar": ("Punjabi", "Romantic/Film", "Deep-Soulful"),
    "Sharry Mann": ("Punjabi", "Romantic/Peppy", "Romantic-Soft"),
    "Jassie Gill": ("Punjabi", "Romantic Pop", "Romantic-Soft"),
    "Millind Gaba": ("Punjabi", "Party Pop", "Energetic"),
    "B Praak": ("Punjabi", "Soulful Ballads", "Deep-Soulful"),
    "Guru Randhawa": ("Punjabi", "Modern Dance-Pop", "Energetic"),
    "Sukha": ("Punjabi", "Modern Pop", "Energetic"),
    "Veet Baljit": ("Punjabi", "Old-School Romantic", "Nostalgic-Classic"),
    "Jatinder Shah": ("Punjabi", "Romantic Composer", "Romantic-Soft"),
    "Prem Dhillon": ("Punjabi", "Modern Pop", "Romantic-Soft"),
    "Pav Dharia": ("Punjabi", "Soft Romantic", "Romantic-Soft"),
    "Mannat Noor": ("Punjabi", "Emotional Female Vocals", "Deep-Soulful"),
    "Jazzy B": ("Punjabi", "Old-School Bhangra", "Energetic"),
    "Harbhajan Mann": ("Punjabi", "Soft/Film", "Nostalgic-Classic"),
    "Lakhwinder Wadali": ("Punjabi", "Sufi Lineage", "Deep-Soulful"),
    "Dr Zeus": ("Punjabi", "UK Bhangra/Dance", "Energetic"),
    "Yo Yo Honey Singh": ("Punjabi", "Rap/Party", "Energetic"),
    "Bhinda Aujla": ("Punjabi", "Folk/Traditional", "Nostalgic-Classic"),
    "Avvy Sra": ("Punjabi", "Modern Pop", "Romantic-Soft"),
    "Arjan Dhillon": ("Punjabi", "Modern Moody Pop", "Deep-Soulful"),
    "Armaan Gill": ("Punjabi", "Modern Romantic", "Romantic-Soft"),
    "VsGakhal": ("Punjabi", "Modern Pop", "Romantic-Soft"),
    "Rajvir Jawanda": ("Punjabi", "Folk-Pop", "Energetic"),
    "prabh gill": ("Punjabi", "Romantic", "Romantic-Soft"),
    "Harrdy Sandhu": ("Punjabi", "Romantic Pop", "Romantic-Soft"),
    "Surinder Kaur": ("Punjabi", "Legendary Folk (40s-60s)", "Nostalgic-Classic"),
    "The PropheC": ("Punjabi", "Diaspora Moody Pop", "Deep-Soulful"),
    "Nachhatar Gill": ("Punjabi", "Old Folk", "Nostalgic-Classic"),
    "Akhil": ("Punjabi", "Romantic Pop", "Romantic-Soft"),
    "Imran Khan": ("Punjabi", "Punjabi-Urdu Pop-Rap", "Energetic"),
    "Jawad Ahmad": ("Punjabi", "Folk-Pop (Pakistani)", "Nostalgic-Classic"),
    "Shae Gill": ("Punjabi", "Sufi-Pop (Coke Studio)", "Deep-Soulful"),
    "Gurshabad": ("Punjabi", "Indie/Sufi-Folk", "Deep-Soulful"),
    "Noor Jehan": ("Punjabi", "Legendary Classic (pre-1960s)", "Nostalgic-Classic"),

    # --- Hindi / Bollywood ---
    "Pritam": ("Hindi", "Bollywood Composer (Versatile)", "Romantic-Soft"),
    "Lata Mangeshkar": ("Hindi", "Legendary Classic Playback", "Nostalgic-Classic"),
    "Kishore Kumar": ("Hindi", "Legendary Classic Playback", "Nostalgic-Classic"),
    "Kumar Sanu": ("Hindi", "90s Romantic Playback", "Nostalgic-Classic"),
    "Jagjit Singh": ("Hindi", "Ghazal", "Deep-Soulful"),
    "Vishal-Shekhar": ("Hindi", "Bollywood Composer", "Energetic"),
    "Rahat Fateh Ali Khan": ("Hindi", "Qawali/Sufi Playback", "Deep-Soulful"),
    "Shankar-Ehsaan-Loy": ("Hindi", "Bollywood Composer", "Romantic-Soft"),
    "Mohammed Rafi": ("Hindi", "Legendary Classic Playback", "Nostalgic-Classic"),
    "Asha Bhosle": ("Hindi", "Legendary Classic Playback", "Nostalgic-Classic"),
    "A.R. Rahman": ("Hindi", "Bollywood Composer (Versatile)", "Deep-Soulful"),
    "Ankit Tiwari": ("Hindi", "Romantic Ballads", "Deep-Soulful"),
    "Tulsi Kumar": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Nusrat Fateh Ali Khan": ("Hindi", "Qawali Legend", "Deep-Soulful"),
    "Mithoon": ("Hindi", "Soulful Ballad Composer", "Deep-Soulful"),
    "Shreya Ghoshal": ("Hindi", "Playback (Versatile)", "Romantic-Soft"),
    "Amit Trivedi": ("Hindi", "Bollywood Composer", "Romantic-Soft"),
    "Shaan": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Akashdeep Sengupta": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Atif Aslam": ("Hindi", "Romantic Playback (Pak)", "Deep-Soulful"),
    "Mukesh": ("Hindi", "Legendary Classic Playback", "Nostalgic-Classic"),
    "Kailash Kher": ("Hindi", "Sufi-Rock", "Deep-Soulful"),
    "Palak Muchhal": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Anuradha Paudwal": ("Hindi", "Classic/Devotional Playback", "Nostalgic-Classic"),
    "Jubin Nautiyal": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Armaan Malik": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Udit Narayan": ("Hindi", "90s-2000s Romantic Playback", "Nostalgic-Classic"),
    "Sunidhi Chauhan": ("Hindi", "Playback (Versatile)", "Energetic"),
    "Meet Bros.": ("Hindi", "Bollywood Composer/Party", "Energetic"),
    "Sachin-Jigar": ("Hindi", "Bollywood Composer", "Energetic"),
    "Sanam": ("Hindi", "Indie Pop Band", "Romantic-Soft"),
    "Jubin Nautiyal ": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Raghav Chaitanya": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Arijit Singh": ("Hindi", "Playback Superstar", "Deep-Soulful"),
    "Darshan Raval": ("Hindi", "Indie/Playback Pop", "Romantic-Soft"),
    "Mustafa Zahid": ("Hindi", "Soulful Rock Ballads", "Deep-Soulful"),
    "KK": ("Hindi", "2000s Soulful Playback", "Deep-Soulful"),
    "The Local Train": ("Hindi", "Indie Rock", "Deep-Soulful"),
    "Sachet Tandon": ("Hindi", "Romantic Playback", "Romantic-Soft"),
    "Sachet-Parampara": ("Hindi", "Romantic Playback Duo", "Romantic-Soft"),
    "Jatin-Lalit": ("Hindi", "90s Bollywood Composer", "Nostalgic-Classic"),
    "Shafqat Amanat Ali": ("Hindi", "Sufi-Pop Playback (Pak)", "Deep-Soulful"),
    "Ajay-Atul": ("Hindi", "Bollywood/Devotional Composer", "Energetic"),
    "Taseer": ("Hindi", "Indie Pop", "Romantic-Soft"),
    "Harshdeep Kaur": ("Hindi", "Sufi/Playback", "Deep-Soulful"),
    "Mahendra Kapoor": ("Hindi", "Classic Playback", "Nostalgic-Classic"),
    "Rawmats": ("Hindi", "Indie Band", "Deep-Soulful"),
}

# Ghazal/Qawali artists get folded into their language bucket above but are
# useful to call out as a distinct cross-cutting "deep/spiritual" genre.
GHAZAL_QAWALI_ARTISTS = {
    "Jagjit Singh", "Rahat Fateh Ali Khan", "Nusrat Fateh Ali Khan",
    "Satinder Sartaaj", "Shafqat Amanat Ali", "Lakhwinder Wadali",
    "Kailash Kher", "Harshdeep Kaur",
}

UNCERTAIN_ARTISTS = {
    "Shashwat Sachdev", "Prismo", "Anne Reburn", "Jaidev Kumar",
    "Vicky", "JERRY", "Bhupinder Gill", "Param Singh",
}
